### ISSUE TITLE
too slow with KVM qcow2 disk

### ISSUE THREAD

**Issue by syssw** [oslab-ewha/MLstorage#2]
I've been testing MLStorage with KVM. BTW, it's too slow if qcow2 disk is used as a backing store.
There's no problem with real SATA disk. What's wrong?

**Comment by cezanne** [comment]
Well, please describe your environments to resolve your issue.

**Comment by syssw** [comment]
@cezanne : Sorry :cry:  The problem was with my KVM settings. Now it works.
